= A Song of Ice and Fire Roleplaing Game: the histories


James Gilmore <james.d.gilmore@gmail.com>; Danny Grosch <Danny.Grosch.96@gmail.com>
Allies of Note:
Ser Osland Ostalon: The finest swordsman in Ostalon and nephew of Lord Barrett, Ser Osland is a large and powerful man who gained his knighthood at age 17. Osland has never been in a true battle before the Battle of Blackwater, though his fighting reputation and well-known ability cause many to anxiously see what this great knight is capable of. 
Unfortunately his spirit was tested at the Battle of Blackwater, and he has returned a bit less than when he left.
Ser Tannis Mercer: A childhood friend of Lord Barrett, Ser Tannis is the castellan of Taloncrag. He once served as master-at-arms, until age got the better of him. His voice was the first to go: now, he is barely able to speak above a hoarse whisper.
Yorel Timbers: Yorel is the lowborn son of a woodcutter, and serves House Ostalon as both the captain of the Ghosts of Taloncrag and as Lord Barrett’s finest scout. Yorel has served House Ostalon faithfully for 16 years.

Lord Arador Ignus: Lord Arador is the Lord of Dawnstone. He is a martial-minded man, and has studied warfare and strategy for years. He’s an arrogant, shallow cunt. If I could get more information about this guy, I’ll post it. Thanks, Obama.
Ser Jason Jeriah II: Better known as Ser Jason the Juggernaut, he has the distinction of being the finest sword in House Ignus. He’s the brother of Lord Jeriah, and his dad was dumb enough to name him after his first-born. Weird. If I could get more information about this guy, I’ll post it. Thanks, Obama.
Ser Derrick Willow: He wears a red hood all of the time because a sharp thing chopped up the back of his head something fierce. He’s a quiet, scheming man who methodically plans actions more than anything. If I could get more information about this guy, I’ll post it. Thanks, Obama.

Lord Jason Jeriah I: Lord Jeriah is the Lord of Lonehall. He distinguished himself in his youth, winning many tournaments, and became well-known for his jousting ability. Others regard him as a genuinely friendly, likeable man. In the Battle of the Western Pass, he was badly wounded fighting against Lord Philip Foote.

Lord Malistair Stormblood: Lord Malistair is a thick and squat man, with a round face and rounder torso. He has a gruff and authoritarian demeanor. He’s a devoted follower of Stannis, though his faith of the Lord of Light is not as zealous as many others. He has shown up very recently with a hundred support noncombatants, 40 sworn swords, and a large band of scouts; he says that he would have brought more, but what little remains of his forces must be kept to protect home.

Lord Bryant Musgood: Lord Musgood is a common sight among the higher courts of Stormlands; many attribute his debutante lifestyle with him more than anything. He is an avid hunter and courtier, though many believe him to be dull-witted and too arrogant to notice. He exhibits all the negative qualities attributed to bad nobility: pompous, short-sighted, egotistical, and arbitrary. At least he’s bringing help: after suffering greatly at the Battle of the Blackwater, Lord Musgood has decided to assist the King’s cause one more time with the few capable men remaining in his service.
Ser Ezra Fartherton: Ser Ezra is a landed knight in service to House Gar. He once captained House Gar’s largest warship, The Gilded Maiden, but it was destroyed during the Battle of Blackwater. Ser Ezra survived, and now leads two-hundred men to support House Ostalon. Ser Ezra stands at six-feet tall, with a great and powerful build, thick muscles, and a barrel-like frame. Strangely, Ser Ezra chooses to march on foot with his men rather than ride on horse while they walk. He has a close rapport with his men, no matter how low their birth, and he can be seen drinking, gambling, and brawling with them during their off-duty.
Ser Richard Horpe: Dark, lean, and hard-eyed, Ser Richard is an accomplished warrior known for both his swordsmanship and steadfast devotion to King Stannis’ cause. He is a pious follower of R’hllor, and has brought 100 equally-zealous Blackwater veterans and 20 sworn swords from various houses to Taloncrag. He claims that they were sent by Stannis himself, to represent him in this conflict and show that House Ostalon has the crown’s support. It’s commonly believed that Ser Richard has a lust for battle, and has earned the nickname of ‘The Slayer’: reportedly a name given by Stannis. A raven recently arrived at Taloncrag reporting Ser Richard’s inevitable arrival in roughly 3 weeks.

Rickard Storm: A broad man with a narrow face, Rickard is the bastard-born brother to Lord Gower. Rickard is broad, but with a narrow face and sharp features. He has been charged with leading the two-hundred Gower men (mostly fresh-faced lads plucked up from the reserves). Although his arrival has been declared by a raven from Lord Gower, they have yet to arrive.

Martyn Tudbury: Martyn is a young man of 15; the second-born son to Lord Tudbury. He is the official commander of the small Tudbury force sent to support Ostalon: 100 men-at-arms, 20 mounted sworn swords, and roughly a hundred noncombatants to provide support for the war effort. Martyn is young and untested, though seems too timid for warfare. He’s recently arrived at Taloncrag with his host, arriving from the sea and marching from Stormblood’s port.

Ser Karl Goldwyn: Karl is the master-at-arms of House Tudbury, and serves as both the de-facto leader of Tudbury’s forces and as Martyn’s bodyguard. He is a barrel-chested man of average height, whose hair has faded to an ashen grey. He is a veteran of multiple wars, and unflinching in both devotion and courage: people have been trying to cut his head off for fourty years, and he’s only learned how to better keep them from doing so. It didn’t help him at the Battle of Henry’s Hill, where he was slain in combat during a Nightthorn charge. 

Ser Ian Penrose: The cousin of Lord Penrose, his house has recently bent the knee to the Iron Throne after the disastrous defeat at the Battle of Blackwater. Ser Ian, a convert of R’hllor, and twenty other like-minded men, have decided to leave their house to support Stannis. They see Ostalon’s conflict as a war for the Southern Stormlands; they believe that the false king Joffery plans on taking the Stormlands from Stannis and want to use the Dornish Marches as a foothold.
Ser Ian is a boisterous and rowdy man, always prepared to both speak his mind and valiantly defend his beliefs in sight of all. He is a transparent, easily-readable man who has no sense of restraint.
He and his twenty heavy cavalrymen are arriving alongside Jeriah and Ignus’ men, but like them, have been stopped at the entrance to the Jagged Pass.

Roland Peasebury: Roland is the third-born, youngest son of House Peasebury. He’s of average height and build, and built with a mean disposition. He has so far proven to be abrasive and overly-serious, and the small force he brought is so far untested...as is his ability to lead them.







Enemies of Note:
Lord Hestor Serpentus, Lord of Castle Scalestone. After a tragic fire 4 years ago, Hestor’s wife, eldest child, and siblings present were killed. Now, only Hestor, his youngest children, and a distant cousin (a grandfather’s brother’s son) carries the Serpentus name. Hestor is a weaselly and tricky man, but has never been known for his skill-at-arms, nor his warfare experience. However, Lord Hestor is a crafty man that knows how to make deals, and when to call for favors.
Ser Gared Vinlen: Master-at-arms at Castle Scalestone. Gared is a thick and hefty man, and a veteran. He fought against House Ostalon during Robert’s Rebellion, and was captured prior to Serpentus’ surrender. He has proven to be a poor commander, and nothing noteworthy in a fight. He’s big, and nothing more. He was shot dead just before the Battle of the Eastern Pass, a crossbow bolt through his visor. The Volantine sellsword captain Varian Nyssos is credited for the shot, taken at 200 yards away, above him on a cliff, at night. 
Ser Voral the Quick: A vassal knight pledged to Serpentus, Ser Voral’s name speaks for himself: he is renowned throughout southern Westeros for his quickness on foot and with a blade. He is likely Hestor’s best fighting man, and probably only man of worth in the whole lot. He was defeated at Henry’s Hill by Ser Osland’s men, but managed to escape with the majority of his force intact.

Lord Alundar Ironwing: Twenty-year old Alundar has recently taken the seat at head of House Ironwing, after his father passed away months ago (around the same time as King Robert’s death). Alundar has no children, as his pregnant wife, Milenna Jast, was killed by outlaws. Alundar is a gentle and cautious man, and has never shown ill-will towards Ostalon. He seems easily pushed and manipulated, and many think that he is a puppet for Ser Ereth.
Alexander Ironwing: Eighteen-year old Alexander serves as Alundar’s personal bodyguard and Captain of the guard at Ironwing. He’s said to be an exceptional fighter for his age, and had shown such at the Melee at Bitterbridge, where he was among the last 20 (out of 116) competitors before being defeated by Loras Tyrell. He was captured at the battle of Henry’s Hill, where his mount was slain in a Stormblood charge and crushed his leg.
Ser Boris Gaunt: A distant relative to House Gaunt, Ser Boris was a close friend of Lord Alundar’s father. He now serves as castellan and magistrate; he is a harsh and unforgiving man, and steadfastly loyal to the advancement of House Ironwing. He has an ironclad sense of duty and justice, and he is known as ‘The Hangman’ due to his severe punishments. He retreated during the battle of Henry’s Hill, only to run into (and be captured by) the hedge knight Ser Creighton Longbough.
Ser Ereth Ironwing: Lord Alundar’s uncle is a thin, wispy man, though known for his skill with a bow. Ser Ereth serves as the House’s steward, and it’s believed that he’s the one who really pulls the strings in House Ironwing. This is bad for Ostalon, as Ser Ereth grew up alongside Hestor, and the two are close friends. Ser Ereth is a poor commander who was easily defeated by Ostalon during Robert’s Rebellion. His youngest son, Eddard, serves as his squire.
Ser Egwin Ironwing: Ser Egwin is the son of Ereth Ironwing. Although a competent fighter, he is nothing special; at the Tourney of Stonehelm four years ago, he was unhorsed in the first round by Osland Ostalon. Egwin is a hot-headed, brash man with more ego than skill. His son, Jensen, is a page under Ser Gared Vinlen’s service.

Lord Philip Foote: Lord of Nightsong and proclaimed Lord of the Marches by the Cunt King Joffery. He was a one-eyed knight of little note before being declared the new Lord of House Foote of Nightsong.
During the Battle of the Blackwater, where Ser Philip of House Foote fought for the combined Lannister-Tyrell army, he kills Lord Bryce Caron, the Lord of Nightsong, in single combat. After the battle the Iron Throne named Philip the new Lord of Nightsong and gives him all the lands, rights and incomes of House Caron.
Lord Anton Jast: The new lord of House Jast of Borderwatch, he is the second son of Lanna Lannister and Lord Antario Jast. His sister was married to Lord Alundar Ironwing before she was killed by outlaws on the road. After the Battle of Blackwater, he was awarded the holdfast of Borderwatch in the Reach. Although House Jast’s main force is occupied with the War, he has arrived with a respectably-sized force of sellswords and mercenaries to help his old friend. He was defeated by Lord Arador Ignus at the battle of the Jagged Pass, and captured.

Ser Henril Nightthorn: Known as the Barbed Knight, Ser Henril is a renowned warrior with a great reputation, both for his viciousness in battle and his charms in court. He is known for his skill at arms on horseback, and he is said to always lead charges personally. The Barbed Knight is the nephew to Lord Gallis Nightthorn. He’s likely entered this conflict for revenge: Lord Barrett Ostalon killed his father during Robert’s Rebellion. He has arrived to Castle Scalestone with an impressive force. He has recently been killed in single combat against Salvandor Ignus.

Ser Tithian Narrows: A hedge knight of little reputation, Ser Tithian leads House Peake’s small force of pikemen and hedge knights from King’s Landing to Castle Scalestone. Ser Tithian is incredibly tall, but has a narrow build and gangly limbs. He was defeated by Lord Musgood at the Jagged Pass, and has retreated inward and escaped.

Ser Deved Lollin: A landed knight in service to House Bolling, Ser Deved is a man of respectable skill. He is a veteran of Robert’s Rebellion, and served as commander for fivescore Lancers that House Bolling has sent to support Serpentus. Deved was gravely wounded in the Ghosts of Taloncrag ambush, and succumbed to his wounds on the pass.

Ser Richard Lonmouth: A famous knight, and arguably the most well-known face amongst the Serpentus supporters. Ser Richard was a close friend and squire to Rhaegar Targaryen, and received his knighthood from the Prince. Ser Richard is a known drunkard, but a deadly fighter and inspiring leader. He defeated Lord Jeriah at the Battle of Jagged Pass.

Ser Ellis Bar Emmon: Ser Ellis is an unimpressive sight: short, round, and portly. He serves as House Buckler’s sworn sword after his house pledged themselves to Stannis. He has arrived to Castle Scalestone with a few hundred men and Lord Buckler’s youngest son, Anders, who serves as his squire.

